<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Toolshed</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="/static/styles/site.css">

        <script>
            function checkUsername(str) {
                if (str.length == 0) {
                    document.getElementById("error").innerText = "";
                    return;
                } else {
                    var xmlhttp = new XMLHttpRequest();
                    xmlhttp.onreadystatechange = function() {
                        if (this.readyState == 4 && this.status == 200) {
                            document.getElementById("error").innerText = this.responseText;
                        }
                    };
                    xmlhttp.open("GET", "/accountNameValidate?q=" + str, true);

                    xmlhttp.send();
                }
            }

            function checkPassword() {
                var password = document.getElementById("password").value;
                var confirmPassword = document.getElementById("confirmPassword").value;
                if (password != confirmPassword || password == "" || confirmPassword == ""){
                    document.getElementById("passCheck").innerText = "Passwords don't match!";
                    document.getElementById("buttonStatus").innerHTML = "<input type = \"submit\" name = \"submit\" class=\"btn btn-primary disabled\" value = \"Create Account\"> <a href = \"<?=$linkTo('loginPage'); ?>\" class = \"btn btn-info\" role=\"button\">Back</a>";
                } else{
                    document.getElementById("passCheck").innerText = "";
                    document.getElementById("buttonStatus").innerHTML = "<input type = \"submit\" name = \"submit\" class=\"btn btn-primary active\" value = \"Create Account\"> <a href = \"<?=$linkTo('loginPage'); ?>\" class = \"btn btn-info\" role=\"button\">Back</a>";
                }
            }
        </script>

    </head>
<div>
<body>
<nav class = "navbar navbar-default">
    <div class = "container-fluid">
        <div class = "navbar-header">
            <a class = "navbar-brand" href="<?= $linkTo('homePage'); ?>">
                <!--<img src ="http://devfloat.net/wp-content/uploads/2016/04/hammers_1.jpg">-->
            </a>
        </div>
        <ul class = "nav navbar-nav">

            <li><a href="<?= $linkTo('loginPage'); ?>">Login</a></li>
            <li><a href="<?= $linkTo('accountCreate'); ?>">Create New Account</a></li>

        </ul>
    </div>
</nav>

<div class="container">
<h1>Create Account</h1>
<form action="<?=$linkTo('accountCreateSubmit'); ?>" method = "post">
    <p>
        Name: <input type = "text" class="form-control col-6" name = "name" required pattern="^[A-Za-z]+$" title="Must only contain Alphabetic characters" placeholder="Enter Name"><br>
        Username: <input type = "text" class="form-control col-6" name = "username" required pattern="^[A-Za-z]+$" title="Must only contain Alphanumeric characters" onkeyup = "checkUsername(this.value)" placeholder="Enter Username"><br>
        <p id = "error"></p>
        Email: <input type = "text"class="form-control col-6"  name = "email" required pattern="^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z{2,3}$" title="Please enter a valid email address e.g. example@gmail.com" placeholder="Enter Email"><br>
        Password: <input type = "password" onkeyup = "checkPassword()" class="form-control col-6" name = "password" required placeholder="Enter Password" id = "password"><br>
        Confirm Password: <input type = "password" onkeyup = "checkPassword()" class="form-control col-6" required name = "password_confirm" placeholder="Enter Password Again" id = "confirmPassword"><br>
    <p id = "passCheck"></p>
    <div id = "buttonStatus">
        <input type = "submit" name = "submit" class="btn btn-primary disabled" value = "Create Account">
        <a href = "<?=$linkTo('loginPage'); ?>" class = "btn btn-info" role="button">Back</a>
    </div>

    </p>

</form>

</div>
<br>
</body>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>