<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Toolshed</title>
        <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
    </head>
<body>

<h1>Create Account</h1>
<form action="<?=$linkTo('accountCreateSubmit'); ?>" method = "post">
    <p>
        Name: <input type = "text" name = "name"><br>
        Username: <input type = "text" name = "username"><br>
        Email: <input type = "text" name = "email"><br>
        Password: <input type = "password" name = "password"><br>
        Confirm Password: <input type = "password" name = "password_confirm"><br>
        <input type = "submit" name = "submit" value = "Create Account"><br>
    </p>

</form>


<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>