<!---------- Header starts --------------->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Toolshed</title>
    <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
    <div>
        <a href="<?= $linkTo('homePage'); ?>">
            <img  src="https://vignette.wikia.nocookie.net/helmet-heroes/images/8/81/Hammer.png/revision/latest?cb=20130708100633">
        </a>
        <a href="<?= $linkTo('browsePage'); ?>">Browse</a>
        <a href="<?= $linkTo('searchPage'); ?>">Search</a>
        <a href="<?= $linkTo('logoutAction'); ?>">Logout</a>
    </div>
</head>
<body>
<!---------- Header ends --------------->