<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<div class="container">
    <div class = "jumbotron">
        <h2>Welcome, <?= $_SESSION["username"];?></h2>
        <h3 class = "text-primary">Instructions:</h3>
        <h5>Navigate to the search page using the navigation bar located at the top. From there, type in the name/ any partial information for the product you're searching for and the results will be displayed below. Alternatively, navigate to the browse page and use the tools in the sidebar to browse and sort through all products in the database. Be sure to log out once you're done!</h5>
    </div>
</div>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>