<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Toolshed</title>
        <link rel="stylesheet" type="text/css" href="/static/styles/site.css">
    </head>
<body>

<h1>Welcome to Toolshed</h1>
<form action="<?= $linkTo('loginSubmit'); ?>" method="post">
    <p>
        Username: <input type = "text" name = "username"><br>
        Password: <input type = "password" name = "password"><br>
        <input type = "submit" name = "login" value = "Log In"><br>
    </p>

</form>


Don't have an account? <a href=<?= $linkTo('accountCreate'); ?>>Register</a><br>
<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>