<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<script>
function searchDB(str) {
        if (str.length == 0) {
            document.getElementById("searchResults").innerHTMl = "";
            return;
        } else {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function() {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("searchResults").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/searchQuery?q=" + str, true);
            xmlhttp.send();
        }
    }
</script>
<div class="container">
    <form>
        <h2 class = "text-primary">Search:</h2>
        <input type ="text" class="form-control" onkeyup = "searchDB(this.value)" placeholder="Search:" name ="search_entered" id = "searchBox">
    </form>
    <div id = "searchResults"></div>
</div>

<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>