<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<script src = search.js>
</script>
<div class="container">
    <form>
        <h2>Search:</h2><input type ="text" class="form-control" onkeyup = "searchDB(this.value)" placeholder="Search:" name ="search_entered" id = "searchBox">
    </form>

        <div id = "searchResults"></div>

</div>

<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>